### ISSUE TITLE
Corporea interaction with ME System non-functional for me (Possible mod interaction?)

### ISSUE THREAD

**Issue by AngelTechnic** [ramidzkh/Applied-Botanics#1] opened 2022-04-26 21:39 UTC
Modlist: https://pastebin.com/4s6GaAJD

I'm struggling to get the interaction between Corporea and the ME system to work at all. Despite updates to AE2 apparently "fixing" the issue, it still persists with me no matter what I do.
![2022-04-26_14 23 59](https://user-images.githubusercontent.com/87926243/165396881-5a28beb1-dd70-45fd-8534-58e2c09ae5f2.png)
![2022-04-26_14 24 03](https://user-images.githubusercontent.com/87926243/165396882-3131dd2a-b3a5-4eba-9345-b562d7f7f30d.png)
Here I'm attempting to extract a stick from a very simple ME system to no avail.

**Comment by ramidzkh** [comment] 2022-04-27 06:34
Can reproduce

**Comment by AngelTechnic** [comment] 2022-04-27 07:19
> Can reproduce

just to be clear, what does this mean?

**Comment by ramidzkh** [comment] 2022-04-27 08:03
> > Can reproduce
> 
> just to be clear, what does this mean?

It means I can get that same bug on my computer. Many times, this is not possible, possibly due to the user having something they didn't report like other mods or a weird OS setup

**Comment by AngelTechnic** [comment] 2022-04-27 08:27
Ah ok, I'm glad I could help

**Comment by ramidzkh** [comment] 2022-04-27 09:25
Fixed in 1.0.1

**Closed as completed by ramidzkh** 2022-04-27 09:25 UTC
Labels: bug
