### ISSUE TITLE
"New version available" notification when using the latest version

### ISSUE THREAD

**Issue by ghost** [ramidzkh/Applied-Botanics#74] opened 2024-11-05 17:23 UTC
On Minecraft 1.20.1 with NeoForge 47.1.106, there's a notification about available update for Applied Botanics. I'm using version 1.5.0 of this mod and this is the latest version available on CurseForge and Modrinth.

**Comment by ramidzkh** [comment] 2024-11-06 01:14
Duplicate of #61. It's not worth fixing for me until 1.6.0 comes out (for a newer MC version)

**Closed as not planned by ramidzkh** 2024-11-06 01:14 UTC

**Comment by jamieb999** [comment] 2024-11-11 21:00
This isn't fixed saying it isn't worth fixing is no reason to close it Reopen this ticket this ticke needs to stay open until it is fixed.

This issue is still ongoing and is not resolved. It isn't a duplicate I had my ticket open a long time ago! 

DO NOT close this ticket!  Wow the dev is just unprofessional doing things like this!  Closing a ticket when it 
isn't fixed. 

I have been waiting a very long time months for this to be fixed and the dev NEVER fixed it and instead
just closed it. Wow this dev is extremely unprofessional. Reopen this ticket immediately! The issue 
is NOT fixed!

**Comment by ghost** [comment] 2024-11-12 11:24
This issue is a duplicate of the one created by you, which is still open. I don't think it's worth it to harass the dev of a free mod because of a very small bug like this.
